### ISSUE TITLE
Error: Cannot find module  (node_modules\babel-loader\lib\index.js)

### ISSUE THREAD

**Issue by fhaute** [symfony/webpack-encore-bundle#162]
Running webpack ...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                           8:31:03 PM

 error  in ../../##DEV/covinated/assets/app.js                                                                                                                                                                    8:31:03 PM

Module build failed (from ../../##DEV/covinated/node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'C:\##DEV\covinated\node_modules\babel-loader\lib\index.js'
Require stack:
- C:\##DEV\covinated\node_modules\loader-runner\lib\loadLoader.js
- C:\##DEV\covinated\node_modules\loader-runner\lib\LoaderRunner.js
- C:\##DEV\covinated\node_modules\webpack\lib\NormalModule.js
- C:\##DEV\covinated\node_modules\@symfony\webpack-encore\lib\webpack-manifest-plugin\index.js
- C:\##DEV\covinated\node_modules\@symfony\webpack-encore\lib\plugins\manifest.js
- C:\##DEV\covinated\node_modules\@symfony\webpack-encore\lib\config-generator.js
- C:\##DEV\covinated\node_modules\@symfony\webpack-encore\index.js
- C:\##DEV\covinated\webpack.config.js
- C:\##DEV\covinated\node_modules\webpack-cli\lib\webpack-cli.js
- C:\##DEV\covinated\node_modules\webpack-cli\lib\bootstrap.js
- C:\##DEV\covinated\node_modules\webpack-cli\bin\cli.js
- C:\##DEV\covinated\node_modules\webpack\bin\webpack.js
- C:\##DEV\covinated\node_modules\@symfony\webpack-encore\bin\encore.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (C:\##DEV\covinated\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\##DEV\covinated\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\##DEV\covinated\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (C:\##DEV\covinated\node_modules\webpack\lib\NormalModule.js:812:3)
    at NormalModule.build (C:\##DEV\covinated\node_modules\webpack\lib\NormalModule.js:956:15)
    at C:\##DEV\covinated\node_modules\webpack\lib\Compilation.js:1367:12

Entrypoint app 13.3 KiB = runtime.js 10.7 KiB app.js 2.61 KiB
webpack compiled with 1 error

**Comment by weaverryan** [comment]
not sure about this - but it's more related to symfony/webpack-encore. However, this looks like some weird dependency issue with Webpack and Babel... or something that downloaded wrong. I'd clear your `node_modules` directory and re-install everything. And maybe also upgrade all of your dependencies.

Cheers!
