### ISSUE TITLE
why install get this qurtions

### ISSUE THREAD

**Issue by bhtomming** [symfony/webpack-encore-bundle#29]
Error: Encore.setOutputPath() cannot be called yet because the runtime environment doesn't appear to be configured. Make sure you're using the encore executable
 or call Encore.configureRuntimeEnvironment() first if you're purposely not calling Encore directly.
    at Object.get (D:\phpstudy\www\drupai\node_modules\@symfony\webpack-encore\index.js:1219:23)
    at Object.<anonymous> (D:\phpstudy\www\drupai\webpack.config.js:5:6)
    at Module._compile (D:\phpStudy\WWW\drupai\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\phpStudy\WWW\drupai\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (D:\phpStudy\WWW\drupai\node_modules\webpack-cli\bin\convert-argv.js:115:13)
    at requireConfig (D:\phpStudy\WWW\drupai\node_modules\webpack-cli\bin\convert-argv.js:117:6)
    at D:\phpStudy\WWW\drupai\node_modules\webpack-cli\bin\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\phpStudy\WWW\drupai\node_modules\webpack-cli\bin\convert-argv.js:122:15)
    at yargs.parse (D:\phpStudy\WWW\drupai\node_modules\webpack-cli\bin\cli.js:232:39)
    at Object.parse (D:\phpStudy\WWW\drupai\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at D:\phpStudy\WWW\drupai\node_modules\webpack-cli\bin\cli.js:210:8
    at Object.<anonymous> (D:\phpStudy\WWW\drupai\node_modules\webpack-cli\bin\cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\phpStudy\WWW\drupai\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\phpStudy\WWW\drupai\node_modules\@symfony\webpack-encore\bin\encore.js:63:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

why use this bundle in symfony4, this is a  lot of problen?

**Comment by weaverryan** [comment]
Hi there! Please open this issue at https://github.com/symfony/webpack-encore - that is the actual Node library. Please also include your full webpack.config.js file and the exact command you're running at the command line so we can help debug.

Cheers!

**Comment by bhtomming** [comment]
I Was use https://github.com/symfony/webpack-encore  but aso has problen

**Comment by bhtomming** [comment]
This is the error message to debug, you dont know what hanpen in this message ?
"Error: Encore.setOutputPath() cannot be called yet because the runtime environment doesn't appear to be configured. Make sure you're using the encore executable"
